### ISSUE TITLE
Copying buffers is slow

### ISSUE THREAD

**Issue by mcollina** [noodlefrenzy/node-amqp-1-0#35]
Copying buffers is slow in node (and maybe everywhere else), so I suggest using [bl](http://npm.im/bl) which does almost the same thing of CircularBuffer but instead maintains the original `Buffer` objects without copying them.

cc @teomurgi

**Comment by noodlefrenzy** [comment]
Yeah, when I first took a dependency on CircularBuffer I assumed they were using a buffer list internally (because that makes sense, right?).  Only later did I dig in and find out the awful truth.  It's been on my list to think about replacing it, so thanks for the recommendation, I'll check into it.
