### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by ltozi** [noodlefrenzy/node-amqp-1-0#38]
Hi, 

I tried to install this module with npm but I have this error caused by CircularBuffer module.

![npm install error](https://cloud.githubusercontent.com/assets/10612162/5998717/ddeafb80-aaca-11e4-8b73-bfd05e7c6622.png)

**Comment by noodlefrenzy** [comment]
Yikes!  Sorry, that's terrible.  I was able to do an install (npm v 1.4.1, windows), so I'm wondering if npm v1.3 doesn't like direct github dependencies (e.g. "module": "user/module" in package.json).

I have a direct dependency on my own fork of CircularBuffer because they haven't accepted a PR for a bugfix I've made and republished.  I'll ping them again, and if I don't hear anything back, I'll publish an alternate version and depend on that one.

**Comment by ltozi** [comment]
Ok, great!
