### ISSUE TITLE
Messages not received

### ISSUE THREAD

**Issue by ltozi** [noodlefrenzy/node-amqp-1-0#40]
Hi, 
It seems that messages bigger than 350 bytes are sent but not received. Is there some size restriction on outgoing messages or I'm missing a particular policy in the receive method?

Thanks

**Comment by noodlefrenzy** [comment]
There is a size restriction of 10k bytes (set in the PolicyBase class - you can override it on construction if you want).

However, I just ran my own test with a message slightly less than 10k through EventHub and was seeing a decoding error, so there might be a decoding issue.  I'm looking into it.

**Comment by noodlefrenzy** [comment]
Hey there, it looks like it was a bug in the way I was encoding large buffers :(  I had a copy-paste issue where large buffers were getting encoded with 0xA0 instead of 0xB0.  I've added a unit-test to ensure the problem is (and remains) resolved.

Please try again, and reopen if you still see a problem.

**Comment by ltozi** [comment]
Ok! It works!
